import Head from "next/head";

import { api } from "@/utils/api";
import Homepage from "@/sections/Homepage";
import Places from "@/sections/Places";
import { Footer } from "@/components/Footer";
import { Services } from "@/sections/Services";
import Testimonials from "@/sections/Testimonials";
import CTABookticket from "@/sections/CTABookticket";
import { Aboutus } from "@/sections/Aboutus";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Beausoleil</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
      <Aboutus/>
      <Services/>
      <CTABookticket/>
      <Places />

      <Testimonials />
      <Footer />
    </>
  );
}
